version: "3"

services:
  csvserver:
    volumes:
     - ./inputFile:/csvserver/inputdata
    ports:
      - "0.0.0.0:9393:9300"
    image: infracloudio/csvserver
    environment:
      - CSVSERVER_BORDER=Orange
  prometheus:
    image: "prom/prometheus:v2.22.0"
    command: "--config.file=/etc/prometheus/prometheus.yml --log.level=debug"
    ports:
      - "9090:9090"
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
